name: Build & Test

on:
  push:
    branches: [ release, develop ]
  pull_request:
    branches: [ release, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install externel dependency library
      run: sudo apt install libaom-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
